# path: k8s/arangodb/pvc.yaml
# version: 1.0
# ArangoDB persistent storage

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arangodb-pvc
  namespace: chatbot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
