# path: k8s/arangodb/secret.yaml
# version: 1.0
# ArangoDB sensitive credentials

apiVersion: v1
kind: Secret
metadata:
  name: arangodb-secret
  namespace: chatbot
type: Opaque
data:
  # changeme (base64 encoded)
  ARANGO_ROOT_PASSWORD: Y2hhbmdlbWU=
