# path: k8s/minio/secret.yaml
# version: 1.0
# MinIO sensitive credentials

apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
stringData:
  # minioadmin (base64 encoded)
  MINIO_ROOT_USER: root
  # minioadmin (base64 encoded)
  MINIO_ROOT_PASSWORD: changememinio
