# File: k8s/n8n/secret.yaml
# Version: 1
apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
type: Opaque
stringData:
  APP_ACCESS_KEY: "app_user"
  APP_SECRET_KEY: "change_me_long_and_random"
  BUCKET_NAME:   "my-archive"
  N8N_OWNER_EMAIL: "admin@app.local"
  N8N_OWNER_PASSWORD: "MyAdmin01"
  N8N_OWNER_FIRST_NAME: "admin"
  N8N_OWNER_LAST_NAME: "admin"
  N8N_USER_MANAGEMENT_JWT_SECRET: "your-very-long-random-jwt-secret-at-least-32-chars"
  N8N_ENCRYPTION_KEY: "your-very-long-random-jwt-secret-at-least-32-chars"