# path: testIngress/kustomization.yaml
# version: 1.0
# Kustomization file for test ingress resources

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chatbot

resources:
  # Namespace
  - namespace.yaml

 # Secrets
  - ingress/ingress-client-ca-secret.yaml
  - ingress/ingress-tls-secret.yaml

  # Configmaps
  - app/configmap.yaml
  - admin/configmap.yaml
  - caddy/configmap.yaml

  # Services
  - app/service.yaml
  - admin/service.yaml
  - caddy/service.yaml
  
  # Deployment
  - app/deployment.yaml
  - admin/deployment.yaml
  - caddy/deployment.yaml

  # Ingress
  - ingress.yaml