# path: k8s/minio/configmap.yaml
# version: 1.0
# MinIO configuration

apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  namespace: chatbot
data:
  MINIO_PORT: "9000"
  MINIO_CONSOLE_PORT: "9001"
