# path: k8s/minio/secret.yaml
# version: 1.0
# MinIO sensitive credentials

apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: chatbot
type: Opaque
data:
  # minioadmin (base64 encoded)
  MINIO_ROOT_USER: bWluaW9hZG1pbg==
  # minioadmin (base64 encoded)
  MINIO_ROOT_PASSWORD: bWluaW9hZG1pbg==
