# path: k8s/arangodb/secret.yaml
# version: 1.0
# ArangoDB sensitive credentials

apiVersion: v1
kind: Secret
metadata:
  name: arangodb-secret
type: Opaque
stringData:
  ARANGO_ROOT_PASSWORD: changeRootMe123
  APP_DB_NAME: chatbot
  APP_USER: arangodbuser
  APP_USER_PASSWORD: changeDbMe123


